[package]
name = "authservice"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.1"
chrono = "0.4.41"
jsonwebtoken = "9.3.1"
serde = "1.0.219"
sqlx = "0.8.6"
tonic = "0.14.2"
tonic-build = "0.14.2"
