edition = "2024"
max_width = 100
tab_spaces = 4
brace_style = "PreferSameLine"
indent_style = "Block"
group_imports = "StdExternalCrate"
trailing_comma = "Vertical"
use_small_heuristics = "Max"  
imports_granularity = "Module"  
use_field_init_shorthand = true