// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message, Serialize, Deserialize)]
pub struct CreateProfileRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message, Serialize, Deserialize)]
pub struct CreateProfileReply {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
